# 実験 II (2023 年度後期) 第 3 回 資料 2

2023.10.10 (火) 第 3, 4 限  
岡田 真

## アヤメのデータセット
データを回収したり作ったり確認したりする．

In [2]:
# -*- coding: utf-8 -*-
from sklearn import datasets
import numpy as np

# アヤメのデータをロードし、変数irisに格納
iris = datasets.load_iris()

# 特徴量のセットを変数Xに、ターゲットを変数yに格納
X = iris.data
y = iris.target

# Xとyをそのまま表示
print(X)
print(y)

# Xとyの次元を表示。それぞれ(150, 4)と(150,)となる。
# サンプル数150, 特徴量の次元4, という意味
print(X.shape)
print(y.shape)

# サンプル数と特徴量の次元の取り出し方法
(n_samples, n_features) = X.shape
print('サンプル数: {0}'.format(n_samples))
print('特徴量の次元: {0}'.format(n_features))

# クラス数の取り出し方法
n_classes = len(np.unique(y))
print('クラス数: {0}'.format(n_classes))


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

### プログラムの確認
ソースコード見てみましょう  


```
# -*- coding: utf-8 -*-
from sklearn import datasets
import numpy as np

# アヤメのデータをロードし、変数irisに格納
iris = datasets.load_iris()

# 特徴量のセットを変数Xに、ターゲットを変数yに格納
X = iris.data
y = iris.target
```

scikit-learn の Python でのパッケージ名が `sklearn` .  
その中のモジュールにいろいろあって，その中の一つが `datasets`．  
`datasets` はデータセットを扱うモジュールで，さまざまなデータセットを中に持っている．  
それに加えてそれらのデータセットのデータを扱うための方法も一緒に持っている．  

この例のソースコードで関係しているところを抜き出すと

```
from sklearn import datasets

# アヤメのデータをロードし、変数irisに格納
iris = datasets.load_iris()
```

この部分で `sklearn` パッケージから `datasets` モジュールを `import` して，そのクラスを変数 `iris` に格納する．  
これで，`iris` は `sklearn` の `datasets` モジュールで定義されたクラスを指している形となる．  
これにより，`iris` はモジュール内で定義されたクラスに従って，インスタンス変数 (`iris.data`，`iris.target`) やインスタンス関数 (`load_iris()`) を利用できるようになる．  

ということで，アヤメのデータセット本体を読み込んでいる．

それからデータとターゲットをそれぞれ変数 `X` と変数 `y` に読み込んでいる．  
データを `X`，ターゲットを `y` とするのは慣例的によくやる．

```
# Xとyをそのまま表示
print(X)
print(y)

# Xとyの次元を表示。それぞれ(150, 4)と(150,)となる。
# サンプル数150, 特徴量の次元4, という意味
print(X.shape)
print(y.shape)
```

13, 14 行目は中身の表示．  
実際にどう入っているか確認．  
18, 19 行目で内容の形式を確認．  
実行したらわかるようにデータ数はどちらも 150 個．  
`X` は特徴量が 4 個なので 150 $\times$ 4 となり，ターゲット `y` は 150 $\times$ 1 となる．

```
# サンプル数と特徴量の次元の取り出し方法
(n_samples, n_features) = X.shape
print('サンプル数: {0}'.format(n_samples))
print('特徴量の次元: {0}'.format(n_features))
```
`shape` で返ってくるタプルの値 `(150, 4)` のそれぞれを変数に入れて表示している．

サンプル数や特徴量の次元の表示で，フォーマット付き文字列の表示方法を使っています．( `C` 言語で `printf()` 関数ってありましたよね？)

Python でもフォーマット付きの表示方法があります．  
大変めんどくさいことに何種類かあって，Python のバージョンで使えたり使えなかったり推奨してたりしてなかったりしてます．  
今回使っている方法は現在のバージョンで使える方法です．  

`'表示したい文字列 {}'.format(表示したい変数やリテラル)`  

という形で書きます．画面で表示されるのはクォーテーションの中身で，その中の波カッコ (`{}`) が `format()` のカッコ内の変数やリテラル (定数) に置き換えられます．
```
'hogehoge {0}, {1}, funifuni'.format(変数0, 変数1)'
```
のように，表示部分に `{}` がいくつかあったら，特に指定がなければ先頭から順番に入れていかれて，「hogehoge <変数 0 の中身>，<変数 1 の中身>，funifuni」のように表示されます．  

ここでは
```
print('サンプル数: {0}'.format(n_samples))
print('特徴量の次元: {0}'.format(n_features))
```
という形でサンプル数と特徴量の次元を表示しています．

```
# クラス数の取り出し方法
n_classes = len(np.unique(y))
print('クラス数: {0}'.format(n_classes))
```
データは `numpy.ndarray` であり，NumPy の形式の配列．  
NumPy の `np.unique()` モジュールを使って，ある NumPy 配列 (`ndarray`) の中の
データの重複なしの個数を取ってくることができる．  
ここでいう "unique (ユニーク)" は "ただ一つの" ということ．  
クラス数は 3 個，各クラスにそれぞれ 0, 1, 2 が割り当てられているのは
前回もやった通り．  
ということで要素 3 個の NumPy 配列が返ってくるので，その要素数を数えて
3 クラスということがわかる．



## 練習 3
上記のソースコードを動かして，結果を確認すること．  
前回の内容とも比較して理解を深めること．  

動作させるのは，Google Colab 上でもローカルマシン上でもどちらでも可．  
できれば両方で動かしてみましょう．